version: '3.3'
services:
  aluraflix-app:
    image: challenge_devops_app
    container_name: aluraflix-app
    volumes:
      - db:/app
    networks:
      - aluraflix-net
    ports:
      - 8000:8000

volumes:
  db:

networks:
  aluraflix-net:
    driver: bridge
    
